---
# Which port the server should listen on.
port: 8080

# Which content types the static server should use. 'if' is a regex that's
# matched against the filename; if it matches, the content type in 'then'
# is sent.
content-types:
  - if: .*\.html?
    then: text/html; charset=utf-8
  - if: .*\.json
    then: application/json; charset=utf-8
  - if: .*\.js
    then: text/javascript; charset=utf-8
  - if: .*\.css
    then: text/css; charset=utf-8
  - if: .*\.svg
    then: image/svg+xml; charset=utf-8
  - if: .*\.png
    then: image/png
  - if: .*\.jpe?g
    then: image/jpeg
  - if: .*\.gif
    then: image/gif
  - if: .*\.ico
    then: image/vnd.microsoft.icon

custom-structures:
  dash:
    paused:
      key: frame.paused

    time:
      current:
        key: game.time
      restRemain:
        key: rest.stop
      navRemain:
        key: truck.navigation.time
        scale: 0.016666666666666666
        operator: round
      jobExpected:
        key: job.delivery.time

    location:
      # Low resolution; used to estimate ambient lighting.
      lat:
        key: truck.world.placement.2
        scale: 0.01
        operator: round
      lon:
        key: truck.world.placement.0
        scale: 0.01
        operator: round

    electric:
      enabled:
        key: truck.electric.enabled
      indicator:
        key: truck.battery.voltage.warning

    engine:
      running:
        key: truck.engine.enabled
      rpm:
        key: truck.engine.rpm
        operator: round
      rpmLimit:
        key: truck.rpm.limit
      wear:
        scale: 100
        operator: round
        key: truck.wear.engine

    transmission:
      mode:
        key: controls.shifter.type
      realGear:
        key: truck.engine.gear
      indicatedGear:
        key: truck.displayed.gear
      diffLock:
        key: truck.differential_lock
      wear:
        scale: 100
        operator: round
        key: truck.wear.transmission

    axles:
      liftTruck:
        key: truck.lift_axle.indicator
      liftTrailer:
        key: truck.trailer.lift_axle.indicator
      speed:
        key: truck.speed
        scale: 100
        operator: round
      odo:
        key: truck.odometer

    brake:
      parking:
        key: truck.brake.parking
      motor:
        key: truck.brake.motor
      retarder:
        key: truck.brake.retarder
      retarderMax:
        key: truck.retarder.steps

    fuel:
      amount:
        key: truck.fuel.amount
        operator: round
      capacity:
        key: truck.fuel.capacity
      consumption:
        key: truck.fuel.consumption.average
        scale: 1000
        operator: round
      indicator:
        key: truck.fuel.warning

    adBlue:
      amount:
        key: truck.adblue
        operator: round
      capacity:
        key: truck.adblue.capacity
      indicator:
        key: truck.adblue.warning

    oil:
      pressure:
        key: truck.oil.pressure
        scale: 10
        operator: round
      indicator:
        key: truck.oil.pressure.warning

    coolant:
      temperature:
        key: truck.water.temperature
        scale: 2
        operator: round
      indicator:
        key: truck.water.temperature.warning

    air:
      pressure:
        key: truck.brake.air.pressure
        scale: 10
        operator: round
      indicator:
        key: truck.brake.air.pressure.warning

    lights:
      parking:
        key: truck.light.parking
      low:
        key: truck.light.beam.low
      high:
        key: truck.light.beam.high
      beacon:
        key: truck.light.beacon
      turnLeft:
        key: truck.light.lblinker
      turnRight:
        key: truck.light.rblinker
      turnSwLeft:
        key: truck.lblinker
      turnSwRight:
        key: truck.rblinker
      turnSwSteer:
        key: truck.effective.steering
        scale: 100
        operator: round
      hazardSw:
        key: truck.hazard.warning
      dash:
        key: truck.dashboard.backlight

    util:
      wipers:
        key: truck.wipers
      cruiseControl:
        key: truck.cruise_control
      speedLimit:
        key: truck.navigation.speed.limit

input:
  binary:
    engine: Toggle engine power
